version: "3.8"

services:
  database:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestPassword123
    # restart: always
    ports:
      - "1433:1433"
    volumes:
      - database-data:/var/opt/mssql
    networks:
      - app-network

  apiserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apiserver
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - FRONTEND_URL=https://personal-planner-client.onrender.com
      - ConnectionStrings__DefaultConnection=Server=database;Database=PersonalPlanner;User Id=sa;Password=TestPassword123;TrustServerCertificate=True;
    networks:
      - app-network
    restart: on-failure

networks:
  app-network:
volumes:
  database-data:
